import type { Contact, EmergencyService, Label } from '../types/contact';
import { detectPakistaniOperator } from './pakistaniTelecom';

export const INITIAL_LABELS: Label[] = [
  { id: 'family', name: 'Family', urduName: 'خاندان', color: '#10B981', isSystem: true },
  { id: 'friends', name: 'Friends', urduName: 'دوست', color: '#3B82F6', isSystem: true },
  { id: 'work', name: 'Work', urduName: 'دفتر', color: '#8B5CF6', isSystem: true },
  { id: 'business', name: 'Business', urduName: 'دکان / کاروبار', color: '#F59E0B', isSystem: true },
  { id: 'emergency', name: 'Emergency', urduName: 'ہنگامی رابطہ', color: '#EF4444', isSystem: true },
];

export const PAKISTANI_EMERGENCY_SERVICES: EmergencyService[] = [
  {
    id: 'rescue-1122',
    name: 'Rescue 1122 (Medical & Fire)',
    urduName: 'ریسکیو 1122 ایمرجنسی سروس',
    shortCode: '1122',
    fullPhone: '042-1122',
    category: 'Rescue & Fire',
    description: 'Emergency ambulance, fire rescue, and disaster relief across Punjab, KPK, & AJK.',
    badgeColor: '#EF4444',
    isAvailable24_7: true,
  },
  {
    id: 'edhi-115',
    name: 'Edhi Ambulance Foundation',
    urduName: 'ایدھی فاؤنڈیشن ایمبولینس',
    shortCode: '115',
    fullPhone: '021-32413232',
    category: 'Medical',
    description: "Pakistan's largest 24/7 free/low-cost nationwide emergency ambulance network.",
    badgeColor: '#10B981',
    isAvailable24_7: true,
  },
  {
    id: 'police-15',
    name: 'Police Emergency Helpline (Madadgar)',
    urduName: 'پولیس مددگار 15',
    shortCode: '15',
    fullPhone: '15',
    category: 'Police & Security',
    description: 'Immediate police response, crime reporting, and city emergency dispatch.',
    badgeColor: '#3B82F6',
    isAvailable24_7: true,
  },
  {
    id: 'chhipa-1020',
    name: 'Chhipa Ambulance Service',
    urduName: 'چھیپا ویلفیئر ایمبولینس',
    shortCode: '1020',
    fullPhone: '021-111-111-020',
    category: 'Medical',
    description: 'Rapid 24/7 emergency response and free ambulance fleet in Sindh and major cities.',
    badgeColor: '#F59E0B',
    isAvailable24_7: true,
  },
  {
    id: 'motorway-130',
    name: 'National Highways & Motorway Police',
    urduName: 'موٹروے پولیس ہیلپ لائن 130',
    shortCode: '130',
    fullPhone: '051-9320293',
    category: 'Highway',
    description: '24/7 highway assistance, accidents, vehicle breakdowns, and travel advisories.',
    badgeColor: '#059669',
    isAvailable24_7: true,
  },
  {
    id: 'fire-16',
    name: 'Fire Brigade Emergency',
    urduName: 'فائر بریگیڈ 16',
    shortCode: '16',
    fullPhone: '16',
    category: 'Rescue & Fire',
    description: 'City municipal fire fighting and building hazard rescue.',
    badgeColor: '#DC2626',
    isAvailable24_7: true,
  },
  {
    id: 'fia-9911',
    name: 'FIA Cyber Crime Reporting',
    urduName: 'ایف آئی اے سائبر کرائم ونگ',
    shortCode: '9911',
    fullPhone: '051-9106384',
    category: 'Police & Security',
    description: 'Reporting online harassment, financial fraud, blackmail, and cyber crimes.',
    badgeColor: '#6366F1',
    isAvailable24_7: false,
  },
  {
    id: 'women-1099',
    name: 'National Women Protection Helpline',
    urduName: 'قومی خواتین تحفظ ہیلپ لائن',
    shortCode: '1099',
    fullPhone: '1099',
    category: 'Human Rights',
    description: 'Ministry of Human Rights helpline for women legal assistance and crisis support.',
    badgeColor: '#EC4899',
    isAvailable24_7: true,
  },
  {
    id: 'railway-117',
    name: 'Pakistan Railways Enquiry',
    urduName: 'پاکستان ریلویز معلوماتی ہیلپ لائن',
    shortCode: '117',
    fullPhone: '117',
    category: 'Utility',
    description: 'Train timings, reservation status, and passenger assistance.',
    badgeColor: '#0284C7',
    isAvailable24_7: true,
  },
];

export const INITIAL_CONTACTS: Contact[] = [
  {
    id: 'pk-cnt-1',
    firstName: 'Dr. Ayesha',
    lastName: 'Siddiqui',
    urduName: 'ڈاکٹر عائشہ صدیقی',
    nickname: 'Ayesha',
    company: 'Shaukat Khanum Memorial Hospital',
    jobTitle: 'Consultant Pediatrician',
    phones: [
      {
        id: 'p1',
        number: '0300 8472910',
        type: 'mobile',
        operator: detectPakistaniOperator('0300 8472910'),
        isPrimary: true,
      },
      {
        id: 'p2',
        number: '042-35905000',
        type: 'work',
        operator: 'other',
      },
    ],
    emails: [
      { id: 'e1', email: 'dr.ayesha.siddiqui@hospital.org.pk', type: 'work' },
    ],
    cnic: '35202-8491024-2',
    cnicProvince: 'Punjab',
    cnicGender: 'Female',
    address: {
      street: 'Street 14, Phase 5, DHA',
      city: 'Lahore',
      province: 'Punjab',
      postalCode: '54792',
    },
    labels: ['work', 'friends'],
    notes: 'Family pediatrician. Consultations on Mon-Thu 4pm to 8pm.',
    birthday: '1988-06-14',
    isStarred: true,
    isFrequent: true,
    avatarColor: '#059669',
    createdAt: '2026-01-15T10:00:00Z',
    updatedAt: '2026-01-15T10:00:00Z',
  },
  {
    id: 'pk-cnt-2',
    firstName: 'Muhammad Bilal',
    lastName: 'Tariq',
    urduName: 'محمد بلال طارق',
    company: 'TechLogix Global',
    jobTitle: 'Principal Cloud Architect',
    phones: [
      {
        id: 'p3',
        number: '0312 9582104',
        type: 'mobile',
        operator: detectPakistaniOperator('0312 9582104'),
        isPrimary: true,
      },
    ],
    emails: [
      { id: 'e2', email: 'bilal.tariq@techlogix.com', type: 'work' },
      { id: 'e3', email: 'bilal.code@gmail.com', type: 'personal' },
    ],
    cnic: '61101-1928475-1',
    cnicProvince: 'Islamabad Capital Territory',
    cnicGender: 'Male',
    address: {
      street: 'House 42, Sector F-8/2',
      city: 'Islamabad',
      province: 'Islamabad Capital Territory',
      postalCode: '44000',
    },
    labels: ['work', 'friends'],
    notes: 'AWS and Google Cloud expert. Mentors local hackathons in Islamabad.',
    website: 'https://bilaltariq.dev',
    isStarred: true,
    isFrequent: true,
    avatarColor: '#2563EB',
    createdAt: '2026-01-18T14:30:00Z',
    updatedAt: '2026-01-18T14:30:00Z',
  },
  {
    id: 'pk-cnt-3',
    firstName: 'Zainab',
    lastName: 'Fatima',
    urduName: 'زینب فاطمہ',
    company: 'Careem Pakistan',
    jobTitle: 'Lead Product Designer',
    phones: [
      {
        id: 'p4',
        number: '0345 2819402',
        type: 'mobile',
        operator: detectPakistaniOperator('0345 2819402'),
        isPrimary: true,
      },
    ],
    emails: [
      { id: 'e4', email: 'zainab.f@careem.com', type: 'work' },
    ],
    cnic: '42101-5839201-4',
    cnicProvince: 'Sindh',
    cnicGender: 'Female',
    address: {
      street: 'Block 4, Clifton',
      city: 'Karachi',
      province: 'Sindh',
      postalCode: '75600',
    },
    labels: ['friends', 'work'],
    notes: 'Organizer at Karachi UX Design Community meetup.',
    isStarred: true,
    isFrequent: false,
    avatarColor: '#9333EA',
    createdAt: '2026-02-01T09:15:00Z',
    updatedAt: '2026-02-01T09:15:00Z',
  },
  {
    id: 'pk-cnt-4',
    firstName: 'Hamza Khan',
    lastName: 'Niazi',
    urduName: 'حمزہ خان نیازی',
    company: 'Niazi Builders & Logistics',
    jobTitle: 'Managing Partner',
    phones: [
      {
        id: 'p5',
        number: '0333 9182740',
        type: 'mobile',
        operator: detectPakistaniOperator('0333 9182740'),
        isPrimary: true,
      },
    ],
    emails: [
      { id: 'e5', email: 'hamza@niazibuilders.pk', type: 'work' },
    ],
    cnic: '17301-4829103-7',
    cnicProvince: 'Khyber Pakhtunkhwa',
    cnicGender: 'Male',
    address: {
      street: 'University Town, Ring Road',
      city: 'Peshawar',
      province: 'Khyber Pakhtunkhwa',
      postalCode: '25000',
    },
    labels: ['business'],
    notes: 'Handles infrastructure material supply across KP and Islamabad.',
    isStarred: false,
    isFrequent: true,
    avatarColor: '#D97706',
    createdAt: '2026-02-10T11:00:00Z',
    updatedAt: '2026-02-10T11:00:00Z',
  },
  {
    id: 'pk-cnt-5',
    firstName: 'Tariq',
    lastName: 'Mehmood',
    urduName: 'طارق محمود (چچا)',
    nickname: 'Tariq Chacha',
    company: 'Chenab Fabrics & Looms',
    jobTitle: 'Factory Director',
    phones: [
      {
        id: 'p6',
        number: '0321 6681023',
        type: 'mobile',
        operator: detectPakistaniOperator('0321 6681023'),
        isPrimary: true,
      },
    ],
    emails: [
      { id: 'e6', email: 'tariq.chenab@gmail.com', type: 'personal' },
    ],
    cnic: '33100-3948201-9',
    cnicProvince: 'Punjab',
    cnicGender: 'Male',
    address: {
      street: 'Millat Town, Canal Road',
      city: 'Faisalabad',
      province: 'Punjab',
      postalCode: '38000',
    },
    labels: ['family', 'business'],
    notes: 'Chacha Tariq in Faisalabad. Export quality cotton yarn supplier.',
    isStarred: true,
    avatarColor: '#0D9488',
    createdAt: '2026-02-12T16:20:00Z',
    updatedAt: '2026-02-12T16:20:00Z',
  },
  {
    id: 'pk-cnt-6',
    firstName: 'Mir Dost',
    lastName: 'Muhammad',
    urduName: 'میر دوست محمد',
    company: 'Chaman Dry Fruit Merchants',
    jobTitle: 'Chief Trader',
    phones: [
      {
        id: 'p7',
        number: '0304 9928174',
        type: 'mobile',
        operator: detectPakistaniOperator('0304 9928174'),
        isPrimary: true,
      },
    ],
    emails: [],
    cnic: '54400-8472910-3',
    cnicProvince: 'Balochistan',
    cnicGender: 'Male',
    address: {
      street: 'Jinnah Road, Near Serena',
      city: 'Quetta',
      province: 'Balochistan',
      postalCode: '87300',
    },
    labels: ['business'],
    notes: 'Wholesale almonds, pistachios, and pine nuts (chilgoza) supplier.',
    isStarred: false,
    avatarColor: '#EA580C',
    createdAt: '2026-02-20T12:00:00Z',
    updatedAt: '2026-02-20T12:00:00Z',
  },
  {
    id: 'pk-cnt-7',
    firstName: 'Sardar Ali',
    lastName: 'Khan',
    urduName: 'سردار علی خان',
    company: 'Neelum Valley Eco Resorts',
    jobTitle: 'Managing Director',
    phones: [
      {
        id: 'p8',
        number: '0355 4910283',
        type: 'mobile',
        operator: detectPakistaniOperator('0355 4910283'),
        isPrimary: true,
      },
    ],
    emails: [
      { id: 'e7', email: 'info@neelumresorts.pk', type: 'work' },
    ],
    cnic: '82201-4920194-5',
    cnicProvince: 'Azad Jammu & Kashmir',
    cnicGender: 'Male',
    address: {
      street: 'Upper Neelum, Keran',
      city: 'Muzaffarabad',
      province: 'Azad Jammu & Kashmir',
      postalCode: '13100',
    },
    labels: ['friends'],
    notes: 'Arranges family travel and guest house bookings in Neelum & Sharda.',
    isStarred: false,
    avatarColor: '#059669',
    createdAt: '2026-02-22T15:00:00Z',
    updatedAt: '2026-02-22T15:00:00Z',
  },
  {
    id: 'pk-cnt-8',
    firstName: 'Usman',
    lastName: 'Ghani',
    urduName: 'عثمان غنی',
    nickname: 'Usman Onic',
    company: 'Freelance Design Studio',
    jobTitle: 'Motion Graphics Animator',
    phones: [
      {
        id: 'p9',
        number: '0319 8472910',
        type: 'mobile',
        operator: detectPakistaniOperator('0319 8472910'),
        isPrimary: true,
      },
    ],
    emails: [
      { id: 'e8', email: 'usman.ghani@studio.pk', type: 'personal' },
    ],
    cnic: '37405-2918472-1',
    cnicProvince: 'Punjab',
    cnicGender: 'Male',
    address: {
      street: 'Satellite Town, Block B',
      city: 'Rawalpindi',
      province: 'Punjab',
      postalCode: '46000',
    },
    labels: ['friends'],
    notes: 'Uses Onic digital SIM. Fast Blender and After Effects contractor.',
    isStarred: false,
    avatarColor: '#7C3AED',
    createdAt: '2026-02-25T11:45:00Z',
    updatedAt: '2026-02-25T11:45:00Z',
  },
  // Intentional duplicate entry for Google Contacts style "Merge & Fix" demo
  {
    id: 'pk-cnt-dup-1',
    firstName: 'Bilal',
    lastName: 'Tariq',
    urduName: 'بلال طارق',
    company: 'TechLogix',
    jobTitle: 'Cloud Engineer',
    phones: [
      {
        id: 'p10',
        number: '0312 9582104', // Matches Muhammad Bilal Tariq above
        type: 'mobile',
        operator: detectPakistaniOperator('0312 9582104'),
        isPrimary: true,
      },
    ],
    emails: [
      { id: 'e9', email: 'bilal.code@gmail.com', type: 'personal' },
    ],
    cnic: '61101-1928475-1',
    cnicProvince: 'Islamabad Capital Territory',
    address: {
      city: 'Islamabad',
      province: 'Islamabad Capital Territory',
    },
    labels: ['work'],
    notes: 'Secondary mobile entry found in phonebook.',
    isStarred: false,
    avatarColor: '#2563EB',
    createdAt: '2026-03-01T08:00:00Z',
    updatedAt: '2026-03-01T08:00:00Z',
  },
];
